[project]
name = "MAT4170"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jax>=0.5.0",
    "matplotlib>=3.10.0",
    "numpy>=2.2.2",
    "pytest>=8.3.4",
]

[tool.uv.workspace]
members = ["mandatory4/src"]
